" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  set undofile		" keep an undo file (undo changes after closing)
endif
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching

" For Win32 GUI: remove 't' flag from 'guioptions': no tearoff menu entries
" let &guioptions = substitute(&guioptions, "t", "", "g")

" Don't use Ex mode, use Q for formatting
map Q gq

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  augroup END

else

  set autoindent		" always set autoindenting on

endif " has("autocmd")

" Convenient command to see the difference between the current buffer and the
" file it was loaded from, thus the changes you made.
" Only define it when not defined already.
if !exists(":DiffOrig")
  command DiffOrig vert new | set bt=nofile | r ++edit # | 0d_ | diffthis
		  \ | wincmd p | diffthis
endif

" Paul's custom settings
let s:VIMROOT = $HOME."/.vim"

set ts=2
set shiftwidth=2
set ai
set expandtab
set number
set guioptions-=l
set guioptions-=L
set guioptions-=r
set guioptions-=R

" for vim-airline
set laststatus=2

nmap <leader>f :NERDTreeToggle<cr>
nnoremap <silent> <C-l> :<C-u>nohlsearch<CR><C-l>
execute pathogen#infect()

silent! call repeat#set("\<Plug>MyWonderfulMap", v:count)

let &backupdir=s:VIMROOT.'/backup//'
let &directory=s:VIMROOT.'/swap//'
let &undodir=s:VIMROOT.'/undo//'

" powerline
" let g:airline_powerline_fonts = 1
" set guifont=Menlo\ For\ Powerline

" color settings
set background=light
" colorscheme solarized " https://github.com/altercation/vim-colors-solarized
colorscheme gruvbox
set background=dark

"if has('gui_running')
"  set background=light
"else
"  set background=dark
"  colorscheme default
"endif


runtime macros/matchit.vim


set number relativenumber
set nu rnu

" https://vim.fandom.com/wiki/Word_wrap_without_line_breaks
set formatoptions=l
set lbr


if has("gui_running")
  if has("gui_gtk2")
    set guifont=Inconsolata\ 12
  elseif has("gui_macvim")
    set guifont=Input\ Mono:h12
  elseif has("gui_win32")
    set guifont=Consolas:h11:cANSI
  endif
endif
